name: first_test
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.3.1"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/Evolution.png
    - assets/Wolf.nima
    - assets/Wolf.png
    - assets/sequence.nima
    - assets/Level_1/Level_1_0001s_0000_Shadow_Trees_B.png
    - assets/Level_1/Level_1_0003s_0001_Stone_5.png
    - assets/Level_1/Level_1_0002s_0001_Crak_2.png
    - assets/Level_1/Level_1_0003s_0004_Stone_4.png
    - assets/Level_1/Level_1_0000s_0003_Trees_Left_B.png
    - assets/Level_1/Level_1_0000s_0001_Trees_Right_B.png
    - assets/Level_1/Level_1_0004s_0001_Floor_A.jpg
    - assets/Level_1/Level_1_0000s_0000_Trees_Right_A.png
    - assets/Level_1/Level_1_0000s_0002_Trees_Left_A.png
    - assets/Level_1/Level_1_0003s_0002_Stone_7.png
    - assets/Level_1/Level_1_0002s_0003_Crack_3.png
    - assets/Level_1/Level_1_0003s_0005_Stone_1.png
    - assets/Level_1/Level_1_0002s_0000_Crack_1.png
    - assets/Level_1/Level_1_0003s_0006_Stone_2.png
    - assets/Level_1/Level_1_0004s_0000_Floor_B.jpg
    - assets/Level_1/Level_1_0001s_0001_Shadow_trees_A.png
    - assets/Level_1/Level_1_0002s_0002_Crak_4.png
    - assets/Level_1/Level_1_0003s_0003_Stone_3.png
    - assets/Level_1/Level_1_0003s_0000_Stoen_6.png
    - assets/Evolution.nima
    - assets/sequence1.png
    - assets/sequence0.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
